# Generated by Django 4.0.5 on 2022-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_rename_services_service_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
