# Generated by Django 4.0.5 on 2022-06-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='image',
        ),
    ]
