# Generated by Django 4.0.5 on 2022-11-10 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_about_image_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_name',
            field=models.CharField(default=datetime.datetime(2022, 11, 10, 7, 49, 46, 902153, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
