# Generated by Django 4.0.5 on 2022-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.FileField(max_length=254, upload_to='documents/'),
        ),
    ]
