# Generated by Django 4.0.5 on 2022-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_about_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='social_contacts',
            new_name='linkedIn',
        ),
        migrations.AddField(
            model_name='footer',
            name='twiter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
