# Generated by Django 4.0.5 on 2022-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_about_image_alter_about_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_server',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
