# Generated by Django 4.0.5 on 2022-06-17 09:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_github_alter_project_live_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='second_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=2, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
