# Generated by Django 4.0.5 on 2022-06-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_second_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='second_phone',
        ),
    ]
