# Generated by Django 4.0.5 on 2022-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
